# Generated by Django 3.2.5 on 2021-07-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='ftwitter_link',
            new_name='twitter_link',
        ),
    ]
